import { useRef } from 'react';
import type { AnalysisData } from '../../types';

interface PDFReportProps {
  data: AnalysisData;
}

export function PDFReport({ data }: PDFReportProps): JSX.Element {
  const reportRef = useRef<HTMLDivElement>(null);

  const { findings, thesisVulnerabilities, metadata } = data;

  // Group findings by slide
  const findingsBySlide = findings.reduce((acc, finding) => {
    if (!acc[finding.slide]) {
      acc[finding.slide] = [];
    }
    acc[finding.slide].push(finding);
    return acc;
  }, {} as Record<number, typeof findings>);

  // Group vulnerabilities by category
  const vulnerabilitiesByCategory = thesisVulnerabilities.reduce((acc, vuln) => {
    if (!acc[vuln.category]) {
      acc[vuln.category] = [];
    }
    acc[vuln.category].push(vuln);
    return acc;
  }, {} as Record<string, typeof thesisVulnerabilities>);

  // Collect all strategic questions
  const allQuestions = findings.flatMap((finding) =>
    finding.strategicQuestions.map((q) => ({
      text: q,
      category: finding.category,
    }))
  );

  // Group questions by category
  const questionsByCategory = allQuestions.reduce((acc, q) => {
    if (!acc[q.category]) {
      acc[q.category] = [];
    }
    acc[q.category].push(q.text);
    return acc;
  }, {} as Record<string, string[]>);

  return (
    <div ref={reportRef} className="pdf-report">
      {/* Page 1: Cover + Executive Summary */}
      <div className="pdf-page">
        <div className="pdf-cover">
          <div className="pdf-header">
            <h1 className="pdf-logo">PITCHGUARD</h1>
            <p className="pdf-subtitle">Due Diligence Report</p>
          </div>

          <div className="pdf-metadata">
            <p className="pdf-meta-item">
              <span className="pdf-meta-label">Company:</span>
              <span className="pdf-meta-value">{metadata.companyName || 'Untitled'}</span>
            </p>
            <p className="pdf-meta-item">
              <span className="pdf-meta-label">Stage:</span>
              <span className="pdf-meta-value">{metadata.fundingStage}</span>
            </p>
            <p className="pdf-meta-item">
              <span className="pdf-meta-label">Analysis Date:</span>
              <span className="pdf-meta-value">
                {new Date().toLocaleDateString('en-US', {
                  month: 'long',
                  day: 'numeric',
                  year: 'numeric',
                })}
              </span>
            </p>
          </div>
        </div>

        <div className="pdf-executive-summary">
          <h2 className="pdf-section-title">Executive Summary</h2>
          <div className="pdf-summary-stats">
            <div className="pdf-stat">
              <p className="pdf-stat-value">{findings.length}</p>
              <p className="pdf-stat-label">Key Findings</p>
            </div>
            <div className="pdf-stat">
              <p className="pdf-stat-value">{thesisVulnerabilities.length}</p>
              <p className="pdf-stat-label">Thesis Vulnerabilities</p>
            </div>
            <div className="pdf-stat">
              <p className="pdf-stat-value">{allQuestions.length}</p>
              <p className="pdf-stat-label">Strategic Questions</p>
            </div>
          </div>
          <p className="pdf-summary-text">
            This report presents a comprehensive analysis of the pitch deck, identifying
            key cognitive biases, thesis vulnerabilities, and strategic questions for due
            diligence. Review each finding in the context of the company's stage and market
            positioning.
          </p>
        </div>

        <div className="pdf-footer">
          <p>Generated by PitchGuard</p>
        </div>
      </div>

      {/* Pages 2-4: Findings by Slide */}
      {Object.entries(findingsBySlide)
        .sort(([a], [b]) => Number(a) - Number(b))
        .map(([slideNum, slideFindings]) => (
          <div key={slideNum} className="pdf-page">
            <div className="pdf-page-header">
              <h2 className="pdf-page-title">
                <span className="pdf-slide-number">Slide {slideNum}</span>
                <span className="pdf-finding-count">
                  {slideFindings.length} {slideFindings.length === 1 ? 'Finding' : 'Findings'}
                </span>
              </h2>
            </div>

            <div className="pdf-findings-list">
              {slideFindings.map((finding, idx) => (
                <div key={finding.id} className="pdf-finding">
                  <div className="pdf-finding-header">
                    <h3 className="pdf-finding-title">
                      <span className="pdf-finding-number">
                        {String(idx + 1).padStart(2, '0')}.
                      </span>
                      {finding.title}
                    </h3>
                    <span className="pdf-finding-tag">{finding.biasTag}</span>
                  </div>
                  <p className="pdf-finding-description">{finding.description}</p>
                  {finding.logicEvidence.signals.length > 0 && (
                    <div className="pdf-finding-signals">
                      <p className="pdf-signals-label">Evidence:</p>
                      <ul className="pdf-signals-list">
                        {finding.logicEvidence.signals.map((signal, i) => (
                          <li key={i}>{signal}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              ))}
            </div>

            <div className="pdf-footer">
              <p>Generated by PitchGuard</p>
            </div>
          </div>
        ))}

      {/* Page 5: Thesis Vulnerabilities */}
      <div className="pdf-page">
        <div className="pdf-page-header">
          <h2 className="pdf-page-title">Thesis Vulnerabilities</h2>
        </div>

        <div className="pdf-vulnerabilities-list">
          {Object.entries(vulnerabilitiesByCategory).map(([category, vulns]) => (
            <div key={category} className="pdf-vulnerability-category">
              <h3 className="pdf-category-title">{category}</h3>
              {vulns.map((vuln, idx) => (
                <div key={vuln.id} className="pdf-vulnerability">
                  <h4 className="pdf-vulnerability-title">
                    <span className="pdf-vulnerability-number">
                      {String(idx + 1).padStart(2, '0')}.
                    </span>
                    {vuln.title}
                  </h4>
                  <p className="pdf-vulnerability-impact">{vuln.impact}</p>
                </div>
              ))}
            </div>
          ))}
        </div>

        <div className="pdf-footer">
          <p>Generated by PitchGuard</p>
        </div>
      </div>

      {/* Pages 6-7: Strategic Questions Checklist */}
      <div className="pdf-page">
        <div className="pdf-page-header">
          <h2 className="pdf-page-title">Strategic Questions Checklist</h2>
        </div>

        <div className="pdf-questions-list">
          {Object.entries(questionsByCategory).map(([category, questions]) => (
            <div key={category} className="pdf-question-category">
              <h3 className="pdf-category-title">{category}</h3>
              {questions.map((question, idx) => (
                <div key={idx} className="pdf-question">
                  <input type="checkbox" className="pdf-checkbox" />
                  <p className="pdf-question-text">{question}</p>
                </div>
              ))}
            </div>
          ))}
        </div>

        <div className="pdf-footer">
          <p>Generated by PitchGuard</p>
        </div>
      </div>
    </div>
  );
}

export function generatePDF(data: AnalysisData): void {
  const { findings, thesisVulnerabilities, metadata } = data;

  // Sort findings by severity (CRITICAL > CONCERN > WATCH)
  const severityOrder = { CRITICAL: 0, CONCERN: 1, WATCH: 2 };
  const sortedFindings = [...findings].sort(
    (a, b) => severityOrder[a.severity] - severityOrder[b.severity]
  );

  // Get top critical findings (top 6-8)
  const criticalFindings = sortedFindings.slice(0, 8);

  // Count findings by severity
  const severityCounts = findings.reduce((acc, f) => {
    acc[f.severity] = (acc[f.severity] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  // Group vulnerabilities by category
  const vulnerabilitiesByCategory = thesisVulnerabilities.reduce((acc, vuln) => {
    if (!acc[vuln.category]) {
      acc[vuln.category] = [];
    }
    acc[vuln.category].push(vuln);
    return acc;
  }, {} as Record<string, typeof thesisVulnerabilities>);

  // Organize questions by priority (based on related finding severity)
  const questionsWithPriority = findings.flatMap((finding) =>
    finding.strategicQuestions.map((q) => ({
      text: q,
      category: finding.category,
      severity: finding.severity,
      findingId: finding.id,
    }))
  );

  // Phase questions by severity
  const phase1Questions = questionsWithPriority.filter((q) => q.severity === 'CRITICAL');
  const phase2Questions = questionsWithPriority.filter((q) => q.severity === 'CONCERN');
  const phase3Questions = questionsWithPriority.filter((q) => q.severity === 'WATCH');

  // Build HTML string
  let html = '<div class="pdf-report">';

  // Page 1: Cover + Executive Overview
  html += `
    <div class="pdf-page">
      <div class="pdf-cover">
        <div class="pdf-header">
          <div class="pdf-accent-bar"></div>
          <h1 class="pdf-logo">PITCHGUARD</h1>
          <p class="pdf-subtitle">Investment Due Diligence Report</p>
        </div>
        <div class="pdf-metadata">
          <p class="pdf-meta-item">
            <span class="pdf-meta-label">Funding Stage</span>
            <span class="pdf-meta-value">${metadata.stage}</span>
          </p>
          <p class="pdf-meta-item">
            <span class="pdf-meta-label">Analysis Date</span>
            <span class="pdf-meta-value">${new Date(metadata.analyzedAt).toLocaleDateString('en-US', {
              month: 'long',
              day: 'numeric',
              year: 'numeric',
            })}</span>
          </p>
          <p class="pdf-meta-item">
            <span class="pdf-meta-label">Deck Size</span>
            <span class="pdf-meta-value">${metadata.slideCount} Slides</span>
          </p>
        </div>
      </div>

      <div class="pdf-executive-summary">
        <h2 class="pdf-section-title">Executive Overview</h2>

        <div class="pdf-key-risks">
          <h3 class="pdf-subsection-title">Key Risk Areas</h3>
          <ul class="pdf-risk-list">
            ${criticalFindings.slice(0, 5).map((finding) => `
              <li class="pdf-risk-list-item">
                <span class="pdf-risk-bullet">●</span>
                <span class="pdf-risk-text">${finding.title}</span>
              </li>
            `).join('')}
          </ul>
        </div>

        <div class="pdf-overview-text">
          <p>This analysis identifies ${findings.length} key findings and ${thesisVulnerabilities.length} thesis vulnerabilities that warrant investigation. The following pages detail critical issues requiring validation, strategic questions for due diligence, and areas that may impact investment decisions.</p>
        </div>
      </div>

      <div class="pdf-footer">
        <p>Generated by PitchGuard • ${new Date().toLocaleDateString()}</p>
      </div>
    </div>
  `;

  // Page 2: Critical Red Flags
  html += `
    <div class="pdf-page">
      <div class="pdf-page-header">
        <h2 class="pdf-page-title">Critical Red Flags</h2>
      </div>

      <p class="pdf-intro-text">The following findings represent the highest-priority issues identified in this analysis. Each requires validation before proceeding with investment decisions.</p>

      <div class="pdf-critical-findings">
        ${criticalFindings.map((finding, idx) => `
          <div class="pdf-critical-finding">
            <div class="pdf-critical-header">
              <div class="pdf-critical-number">${String(idx + 1).padStart(2, '0')}</div>
              <div class="pdf-critical-content">
                <h3 class="pdf-critical-title">${finding.title}</h3>
                <div class="pdf-critical-meta">
                  <span class="pdf-critical-badge">${finding.biasTag}</span>
                  <span class="pdf-critical-divider">•</span>
                  <span class="pdf-critical-slide">Slide ${finding.slide}</span>
                </div>
              </div>
            </div>

            <div class="pdf-critical-body">
              <div class="pdf-critical-section">
                <p class="pdf-critical-label">Why This Matters</p>
                <p class="pdf-critical-text">${finding.description}</p>
              </div>

              ${finding.logicEvidence.signals.length > 0 ? `
                <div class="pdf-critical-section">
                  <p class="pdf-critical-label">Evidence Observed</p>
                  <ul class="pdf-critical-signals">
                    ${finding.logicEvidence.signals.map((signal) => `
                      <li>${signal}</li>
                    `).join('')}
                  </ul>
                </div>
              ` : ''}

              ${finding.strategicQuestions.length > 0 ? `
                <div class="pdf-critical-section">
                  <p class="pdf-critical-label">What to Validate</p>
                  <ul class="pdf-critical-questions">
                    ${finding.strategicQuestions.slice(0, 2).map((q) => `
                      <li>${q}</li>
                    `).join('')}
                  </ul>
                </div>
              ` : ''}
            </div>
          </div>
        `).join('')}
      </div>

      <div class="pdf-footer">
        <p>Generated by PitchGuard</p>
      </div>
    </div>
  `;

  // Page 5: Thesis Vulnerabilities
  html += `
    <div class="pdf-page">
      <div class="pdf-page-header">
        <h2 class="pdf-page-title">Thesis Vulnerabilities</h2>
      </div>
      <div class="pdf-vulnerabilities-list">
  `;

  Object.entries(vulnerabilitiesByCategory).forEach(([category, vulns]) => {
    html += `
      <div class="pdf-vulnerability-category">
        <h3 class="pdf-category-title">${category}</h3>
    `;

    vulns.forEach((vuln, idx) => {
      html += `
        <div class="pdf-vulnerability">
          <h4 class="pdf-vulnerability-title">
            <span class="pdf-vulnerability-number">${String(idx + 1).padStart(2, '0')}.</span>
            ${vuln.title}
          </h4>
          <p class="pdf-vulnerability-impact">${vuln.impact}</p>
        </div>
      `;
    });

    html += '</div>';
  });

  html += `
      </div>
      <div class="pdf-footer">
        <p>Generated by PitchGuard</p>
      </div>
    </div>
  `;

  // Page 4: Strategic Due Diligence Framework
  html += `
    <div class="pdf-page">
      <div class="pdf-page-header">
        <h2 class="pdf-page-title">Due Diligence Framework</h2>
      </div>

      <p class="pdf-intro-text">Questions organized by priority to guide systematic validation. Start with Phase 1 (deal-breakers), then Phase 2 (deep dive), and Phase 3 (final verification).</p>

      ${phase1Questions.length > 0 ? `
        <div class="pdf-dd-phase">
          <div class="pdf-phase-header">
            <span class="pdf-phase-badge critical-badge">Phase 1</span>
            <h3 class="pdf-phase-title">Initial Validation — Deal Breakers</h3>
          </div>
          <div class="pdf-phase-questions">
            ${phase1Questions.slice(0, 8).map((q) => `
              <div class="pdf-dd-question">
                <input type="checkbox" class="pdf-checkbox critical-check" />
                <p class="pdf-dd-text">${q.text}</p>
              </div>
            `).join('')}
          </div>
        </div>
      ` : ''}

      ${phase2Questions.length > 0 ? `
        <div class="pdf-dd-phase">
          <div class="pdf-phase-header">
            <span class="pdf-phase-badge concern-badge">Phase 2</span>
            <h3 class="pdf-phase-title">Deep Dive — Serious Consideration</h3>
          </div>
          <div class="pdf-phase-questions">
            ${phase2Questions.slice(0, 8).map((q) => `
              <div class="pdf-dd-question">
                <input type="checkbox" class="pdf-checkbox concern-check" />
                <p class="pdf-dd-text">${q.text}</p>
              </div>
            `).join('')}
          </div>
        </div>
      ` : ''}

      ${phase3Questions.length > 0 ? `
        <div class="pdf-dd-phase">
          <div class="pdf-phase-header">
            <span class="pdf-phase-badge watch-badge">Phase 3</span>
            <h3 class="pdf-phase-title">Final Verification</h3>
          </div>
          <div class="pdf-phase-questions">
            ${phase3Questions.slice(0, 6).map((q) => `
              <div class="pdf-dd-question">
                <input type="checkbox" class="pdf-checkbox watch-check" />
                <p class="pdf-dd-text">${q.text}</p>
              </div>
            `).join('')}
          </div>
        </div>
      ` : ''}

      <div class="pdf-footer">
        <p>Generated by PitchGuard</p>
      </div>
    </div>
  `;

  html += '</div>';

  // Create a temporary container
  const container = document.createElement('div');
  container.innerHTML = html;
  container.id = 'pdf-print-container';

  // Hide off-screen for regular display, but visible during print
  container.style.cssText = `
    position: fixed;
    top: -9999px;
    left: -9999px;
    width: 100%;
  `;

  document.body.appendChild(container);

  // Trigger print
  setTimeout(() => {
    window.print();

    // Cleanup after print dialog closes
    setTimeout(() => {
      if (document.body.contains(container)) {
        document.body.removeChild(container);
      }
    }, 500);
  }, 100);
}
